name: Deploy Node.js Backend to Azure Web App - SayHi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Zip server folder
        run: |
          cd server
          zip -r ../server.zip .

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-zip
          path: server.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: server-zip

      - name: Unzip for deployment
        run: unzip server.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SayHi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
